### PR TITLE
Add hardware project files (KiCad)

### PR DESCRIPTION
**Pull request by ngandrass**
This PR adds the full KiCad project files of the badge

### CODE REVIEW

**Comment by DunkelRatte** [comment]
Some text in there references "Arial" - we should probably fix that before merging

**Comment by ngandrass** [comment]
Found the sucker! :D Preparing a patch now
image

**Comment by DunkelRatte** [comment]
> KiCad will fall back to another font if it didn't find Arial. I'll give this 5 minutes to find it and will merge anyway otherwise. People start to ask for it ^^'

yeah. but it will throw an error every time you open it

**Comment by ngandrass** [comment]
Grepped through the whole project files and removed all Arial usages :+1:

**Pull request merged**
