### PR TITLE
Improve MainMenu, add brightness control

### PR DESCRIPTION
**Pull request by TokenRat**
Improve MainMenu, add brightness control

Somehow it is not yet correctly persisted. I think I am loading globals incorrectly in main.cpp and that makes it reset this to the default value.

### CODE REVIEW

**Comment by TokenRat** [comment]
Based on #24 , merge this one first.

**Comment by ngandrass** [comment]
For persistence you also need to add add the values to `FSM::persistGlobals()` and `FSM::restoreGlobals()`.

See for an example: https://github.com/eurofurence/ef28-badge/pull/19/commits/2eed4363c65208c6c3b4af03797bdb4e83b1f7d5

**Review by ngandrass — CHANGES_REQUESTED** [review]
There is a 15-character limit for keys in `Preferences` / NVS. This most likely causes problems.

> Namespace and key names are character strings and are limited to a maximum of 15 characters.

See: https://docs.espressif.com/projects/arduino-esp32/en/latest/tutorials/preferences.html#preferences-attributes

**Review by ngandrass — APPROVED** [review]
I pushed a potential fix but cannot test it right now.

@TokenRat Please test, confirm its working properly, and merge if you like :+1:

**Comment by ngandrass** [comment]
Ok, there were more problems. A second `FSMGlobals` instance was created and the brightness was tried to be set before the values were read from the NVS. Now it should work and I did a super quick test on hardware.

Please test yourself and merge afterwards :heart:

**Pull request merged**
